config/routes.rb
TasksAboutSatellites::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :tasks
  resources :solutions, path: "tasks/:id", as: :solutions, only: :create
  resources :solutions, only: [:show, :index]

  root 'static_pages#home'

  match '/help', to: 'static_pages#help', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/news', to: 'static_pages#news', via: 'get'

  match '/signup', to: 'users#new', via: 'get'

  match '/builder', to: 'tasks#new', via: 'get'

  match '/signin',  to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'

end

app/models/task.rb
class Task < ActiveRecord::Base
  has_many :solutions, dependent: :destroy
  has_many :users, through: :solutions
  default_scope -> { order('created_at ASC') }

  validates :name, presence: true, length: { maximum: 60 }
  validates :content, presence: true, length: { maximum: 1500 }
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :signed_in_user
  before_action :admin_user, only: [:new, :create, :destroy, :edit, :update]

  # нужно посмотреть, как табличку сделать
  def index
    @tasks = Task.paginate(page: params[:page])
  end

  def show
    @task = Task.find(params[:id])
    @solution = @task.solutions.build
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    if @task.save
      flash[:success] = "Ура! Вы пополнили орбиту спутниками. :)"
      redirect_to @task
    else
      render 'new'
    end
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    if @task.update_attributes(task_params)
      flash[:success] = "Задача обновлена."
      redirect_to @task
    else
      render 'edit'
    end
  end

  def destroy
    Task.find(params[:id]).destroy
    flash[:success] = "Задача удалена."
    redirect_to tasks_url
  end

  private

  def task_params
    params.require(:task).permit(:name, :content, :formula)
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <%= f.label :name, 'Название' %>
  <%= f.text_field :name %>
  <%= f.label :content, 'Текст задачи' %>
  <%= f.text_area :content %>
  <%= f.label :formula, 'Функция' %>
  <%= f.text_field :formula, id: "formulaInput" %>      <%= f.submit "Сохранить", class: "btn btn-large btn-primary" %>
<% end %>
<h4>
  <p>Специальные символы:</p>
</h4>
<span>
  <button onClick="insertThisInThere('∀','formulaInput');">∀</button>
  <button onClick="insertThisInThere('∃','formulaInput');">∃</button>
  <button onClick="insertThisInThere('∄','formulaInput');">∄</button>
  <button onClick="insertThisInThere('∅','formulaInput');">∅</button>
  <button onClick="insertThisInThere('∈','formulaInput');">∈</button>
  <button onClick="insertThisInThere('∉','formulaInput');">∉</button>
  <button onClick="insertThisInThere('⊂','formulaInput');">⊂</button>
  <button onClick="insertThisInThere('⊃','formulaInput');">⊃</button>
  <button onClick="insertThisInThere('⊄','formulaInput');">⊄</button>
  <button onClick="insertThisInThere('⊅','formulaInput');">⊅</button>
  <button onClick="insertThisInThere('⩽','formulaInput');">⩽</button>
  <button onClick="insertThisInThere('⩾','formulaInput');">⩾</button>
  <button onClick="insertThisInThere('¬','formulaInput');">¬</button>
  <button onClick="insertThisInThere('∧','formulaInput');">∧</button>
  <button onClick="insertThisInThere('∨','formulaInput');">∨</button>
  <button onClick="insertThisInThere('⊕','formulaInput');">⊕</button>
  <button onClick="insertThisInThere('⟶','formulaInput');">⟶</button>
  <button onClick="insertThisInThere('⟷','formulaInput');">⟷</button>
  <button onClick="insertThisInThere('','formulaInput');"></button>
  <button onClick="insertThisInThere('∣','formulaInput');">∣</button>
</span>

app/views/tasks/_task.html.erb
<tr>
  <td>
    <%= "#{task.id}" %>
  </td>
  <td>
    <%= link_to task.name, task %>
  </td>
</tr>

app/views/tasks/edit.html.erb
<% provide(:title, "Редактирование данных задачи") %>
<h1>Обновление данных задачи</h1>
<div class="row">
  <div class="span12">
    <%= render 'tasks/form' %>
  </div>
</div>

app/views/tasks/index.html.erb
<% provide(:title, 'Задачи') %>
<h1>Список задач</h1>
<%= link_to("Добавить", builder_path, class: "btn") if current_user.admin? %>
<%= will_paginate %>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Номер</th>
      <th>Название</th>
    </tr>
  </thead>
  <tbody>
    <%= render @tasks %>
  </tbody>
</table>
<%= will_paginate %>

app/views/tasks/new.html.erb
<% provide(:title, 'Создание задачи') %>
<h1>Сотворение новой задачи</h1>
<div class="row">
  <div class="span12">
    <%= render 'tasks/form' %>
  </div>
</div>

app/views/tasks/show.html.erb
<% provide(:title, @task.name) %>
<div class="row">
  <div class="span3">
    <br>
    <%= link_to "Изменить", edit_task_path(@task), class: "btn" if current_user.admin? %>
    <%= link_to "Удалить", @task, method: :delete, class: "btn btn-inverse", 
      data: { confirm: "Вы уверены?" } if current_user.admin? %>
  </div>
  <div class="span3 offset6">
    <h1>Задача <%= @task.id %></h1>
  </div>
  <div class="span6">
    <h3><%= @task.name %></h3>
  </div>
  <div class="span12">
    <p>
      <%= @task.content %>
    </p>
  </div>
  <div class="span12">
    <div class="row">
      <div class="span2">
        <h4>
          <p>Функция: </p>
        </h4>
      </div>
      <div class="span10">
        <pre class="formula"><%= @task.formula %></pre>
      </div>
    </div>
  </div>
  <div class="span12">
    <!-- input field -->
  </div>
  <div class="span12">
    <!-- outputfield -->
  </div>
  <div class="span7 offset1">
    <%= render 'solutions/form' %>
  </div>
</div>