config/routes.rb
TasksAboutSatellites::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :tasks
  resources :solutions, path: "tasks/:id", as: :solutions, only: :create
  resources :solutions, only: [:show, :index]

  root 'static_pages#home'

  match '/help', to: 'static_pages#help', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/news', to: 'static_pages#news', via: 'get'

  match '/signup', to: 'users#new', via: 'get'

  match '/builder', to: 'tasks#new', via: 'get'

  match '/signin',  to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://vk.com/geraltzrivii">vk: GeraltZRivii</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "О нас", about_path %></li>
      <li><%= link_to "Контакты", '#' %></li>
      <li><%= link_to "Правила", '#' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container-fluid">
      <%= link_to "Мир Спутников", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Главная", root_path %></li>
          <li><%= link_to "Новости", news_path %></li>
          <li><%= link_to "Помощь", help_path %></li>
          <% if signed_in? %>
            <li><%= link_to "Пользователи", users_path %></li>
            <li><%= link_to "Архив задач", tasks_path %></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <%= current_user.name %> <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Профиль", current_user %></li>
                <li><%= link_to "Настройки", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Выход", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Вход", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
    <script type="text/javascript">
      SyntaxHighlighter.all();
    </script>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "alert alert-#{key} flash-alert") %>
      <% end %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>